//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixMVCCrud.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_General_Data
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> General_Type_ID { get; set; }
    
        public virtual Employees_General_Type Employees_General_Type { get; set; }
    }
}
