//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixMVCCrud.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatrixMVCCrudDBEntities : DbContext
    {
        public MatrixMVCCrudDBEntities()
            : base("name=MatrixMVCCrudDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employees_General_Data> Employees_General_Data { get; set; }
        public virtual DbSet<Employees_General_Type> Employees_General_Type { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
